CREATE DATABASE Projeto_DS2020batata;

USE Projeto_DS2020batata;

CREATE TABLE Credencial
(
idusuario INT PRIMARY KEY IDENTITY(1,1),
usuario VARCHAR(100) UNIQUE NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
senha VARCHAR(50) NOT NULL,
tipo VARCHAR(100) NOT NULL,
)

SELECT * FROM credencial;

